name: CMake

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: archlinux

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: pacman -S cmake sdl2 cunit

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build

      - name: Build
        run: cmake --build ${{github.workspace}}/build

      - name: Test
        working-directory: ${{github.workspace}}/build/tests
        run: test

